"""Bundle src/apex_attack/* into a single submission/attack.py.

Kaggle evaluator imports attack.py from /kaggle/working — it must be
self-contained (no src/ package). This script inlines the modules in
dependency order and verifies the bundle compiles + exposes AttackAlgorithm.
"""
from __future__ import annotations
import ast
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "apex_attack"
OUT = ROOT / "submission" / "attack.py"

# Order matters: config -> primitives/labels -> primitives/templates -> core -> search -> facade
MODULES = [
    SRC / "config.py",
    SRC / "primitives" / "labels.py",
    SRC / "primitives" / "templates.py",
    SRC / "core" / "scoring.py",
    SRC / "core" / "guardrail.py",
    SRC / "search" / "structures.py",
    SRC / "search" / "race.py",
    SRC / "search" / "fill.py",
]

HEADER = '''"""Apex Attack — bundled submission build.

Source lives in src/apex_attack/ (modular); this file is generated by tools/bundle.py.
Do not edit by hand — edit src/ and re-bundle.

Config/primitives/core/search modules are inlined below in dependency order,
followed by the AttackAlgorithm facade that stitches them together.
"""
from __future__ import annotations
'''

def strip_module_header(src: str) -> str:
    lines = src.splitlines()
    out: list[str] = []
    in_apex_import = False
    paren_depth = 0
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("from __future__"):
            continue
        if in_apex_import:
            # count parens to know when multi-line import ends
            paren_depth += line.count("(") - line.count(")")
            if ")" in line or paren_depth <= 0:
                in_apex_import = False
                paren_depth = 0
            continue
        if stripped.startswith("from apex_attack") or stripped.startswith("import apex_attack"):
            # start of apex import — may be multi-line
            if "(" in line and ")" not in line:
                in_apex_import = True
                paren_depth = line.count("(") - line.count(")")
            continue
        out.append(line)
    return "\n".join(out)

def main():
    parts = [HEADER]
    for mod in MODULES:
        rel = mod.relative_to(ROOT)
        src = mod.read_text(encoding="utf-8")
        body = strip_module_header(src)
        parts.append(f"\n# === {rel} ===\n")
        parts.append(body)
    # Append facade (already has SDK discovery + AttackAlgorithm)
    facade = (SRC / "attack.py").read_text(encoding="utf-8")
    facade_body = strip_module_header(facade)
    # facade's own _add_sdk_root uses local imports — keep it but remove apex_attack imports
    # Re-inject standard imports that strip removed
    parts.append("\n# === src/apex_attack/attack.py (facade) ===\n")
    parts.append(facade_body)
    bundled = "\n".join(parts)
    OUT.write_text(bundled, encoding="utf-8")
    try:
        ast.parse(bundled)
    except SyntaxError as e:
        # Show context around error for debugging but keep file for inspection
        lines = bundled.splitlines()
        start = max(0, e.lineno - 8)  # type: ignore
        end = min(len(lines), (e.lineno or 0) + 8)
        ctx = "\n".join(f"{i+1:4d}: {lines[i]}" for i in range(start, end))
        print(f"[bundle] SyntaxError at line {e.lineno}: {e.msg}\n{ctx}")
        raise
    # Verify import
    import importlib.util, sys
    spec = importlib.util.spec_from_file_location("attack_bundle_check", OUT)
    mod = importlib.util.module_from_spec(spec)  # type: ignore
    sys.modules["attack_bundle_check"] = mod
    assert spec and spec.loader
    spec.loader.exec_module(mod)  # type: ignore
    assert hasattr(mod, "AttackAlgorithm"), "bundle missing AttackAlgorithm"
    print(f"[bundle] {OUT} ({len(bundled)} bytes) — OK, AttackAlgorithm present")

if __name__ == "__main__":
    main()
